name: frmatch
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - adjusttext=1.3.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h5da7b33_9
  - brotlicffi=1.0.9.2=py312h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.6.15=py312haa95532_0
  - cffi=1.17.1=py312h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py312h214f63a_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - double-conversion=3.3.1=h5da7b33_0
  - expat=2.6.4=h8ddb27b_0
  - filelock=3.17.0=py312haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h765892d_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py312h827c3e9_0
  - freetype=2.13.3=h57928b3_1
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py312h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=11.0.0=h9e37d49_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=75.1=he0c23c2_0
  - idna=3.7=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.4.2=py312haa95532_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.8=py312h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h5da7b33_0
  - libclang13=20.1.8=default_hadf22e1_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_3
  - libglib=2.84.0=h7025463_0
  - libgomp=15.1.0=h1383e82_3
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libpng=1.6.50=h95bef1e_0
  - libsqlite=3.50.2=hf5d6505_2
  - libtiff=4.7.0=hfc51747_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.41=h0739af5_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib=3.10.3=py312h2e8e312_0
  - matplotlib-base=3.10.3=py312h90004f6_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py312haa95532_0
  - networkx=3.4.2=py312haa95532_0
  - numpy=2.0.1=py312hfd52020_1
  - numpy-base=2.0.1=py312h4dde369_1
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.1=h725018a_0
  - packaging=24.2=py312haa95532_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py312hfb502af_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=had0cd8c_0
  - pthread-stubs=0.3=h3c9f919_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyside6=6.9.0=py312h520aab8_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.7=hce54a09_0_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python_abi=3.12=7_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py312h827c3e9_0
  - qhull=2020.2=h59b6b97_2
  - qt6-main=6.9.0=h83cda92_0
  - requests=2.32.4=py312haa95532_0
  - scikit-learn=1.6.1=py312h585ebfc_0
  - scipy=1.15.3=py312h180bac5_0
  - setuptools=78.1.1=py312haa95532_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.13.3=py312haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.1=py312h827c3e9_0
  - typing_extensions=4.12.2=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py312h827c3e9_1
  - urllib3=2.5.0=py312haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - torchaudio==2.5.1
      - torchvision==0.20.1
prefix: S:\anaconda\envs\frmatch
